In [ ]:
import numpy

In [ ]:
pip install numpy

In [1]:
import numpy

In [2]:
import numpy as np

In [22]:
a=np.array([(1,2,3,4),(4,5,6,6)])

In [24]:
print(a)

[[1 2 3 4]
 [4 5 6 6]]


In [7]:
c=np.transpose(a)

In [9]:
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
c.ravel()

array([1, 4, 2, 5, 3, 6])

In [11]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [27]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 6]])

In [35]:
ze=np.ones((10,12))

In [36]:
print(ze)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [38]:
np.random.random((10,12))

array([[0.1931191 , 0.96358522, 0.34923211, 0.79560092, 0.65758063,
        0.078073  , 0.92780574, 0.58849665, 0.64065396, 0.53952782,
        0.38794443, 0.73964524],
       [0.84433237, 0.77117438, 0.01510275, 0.55010493, 0.73785936,
        0.3625501 , 0.96212022, 0.88534962, 0.67063273, 0.38066262,
        0.41358532, 0.38286223],
       [0.50282744, 0.81701072, 0.25971985, 0.44155165, 0.92083184,
        0.07598567, 0.08979236, 0.20307513, 0.04094825, 0.813563  ,
        0.6462199 , 0.10497226],
       [0.7719253 , 0.84322125, 0.72632545, 0.21520839, 0.85187705,
        0.87546818, 0.32450751, 0.16458421, 0.38218753, 0.67557881,
        0.46633717, 0.34586839],
       [0.2858296 , 0.87872582, 0.80288816, 0.07318381, 0.78128085,
        0.09829224, 0.73162538, 0.80129717, 0.02335463, 0.27049114,
        0.79385726, 0.17596987],
       [0.1159478 , 0.52961474, 0.38919807, 0.76977233, 0.00501489,
        0.25569448, 0.55829536, 0.94412559, 0.18540043, 0.44898305,
        0.35363171,